"""initial schema

Revision ID: 56e2fcad7b76
Revises: 
Create Date: 2026-09-30 18:28:51.286240
"""
from alembic import op
import sqlalchemy as sa


revision = '56e2fcad7b76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('engine', sa.Enum('HTTP', 'PLAYWRIGHT', name='engine_type'), nullable=False),
    sa.Column('parser_config', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('oem', sa.String(length=100), nullable=True),
    sa.Column('cross_numbers', sa.JSON(), nullable=False),
    sa.Column('applicability', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=300), nullable=True),
    sa.Column('subcategory', sa.String(length=300), nullable=True),
    sa.Column('first_seen_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_article', 'products', ['article'], unique=False)
    op.create_index('ix_products_brand', 'products', ['brand'], unique=False)
    op.create_index('ix_products_oem', 'products', ['oem'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', 'ON_ORDER', 'MANY', 'UNKNOWN', name='stock_status'), nullable=False),
    sa.Column('warehouse', sa.String(length=300), nullable=True),
    sa.Column('delivery_time', sa.String(length=200), nullable=True),
    sa.Column('disappeared', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('last_seen_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('last_changed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url', name='uq_offer_competitor_url')
    )
    op.create_index('ix_offers_product_competitor', 'offers', ['product_id', 'competitor_id'], unique=False)
    op.create_table('parse_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'OK', 'ERROR', name='run_status'), nullable=False),
    sa.Column('trigger', sa.Enum('AUTO', 'MANUAL', name='run_trigger'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('products_found', sa.Integer(), nullable=False),
    sa.Column('products_new', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_metrics',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sales_1d', sa.Integer(), nullable=False),
    sa.Column('sales_7d', sa.Integer(), nullable=False),
    sa.Column('sales_14d', sa.Integer(), nullable=False),
    sa.Column('sales_30d', sa.Integer(), nullable=False),
    sa.Column('sales_60d', sa.Integer(), nullable=False),
    sa.Column('sales_90d', sa.Integer(), nullable=False),
    sa.Column('avg_daily_demand', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sales_frequency_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('days_observed', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=4), nullable=False),
    sa.Column('demand_index', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('competitors_count', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_avg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_median', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('replenishments_7d', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('change_type', sa.Enum('SALES', 'REPLENISHMENT', 'PRICE_DOWN', 'PRICE_UP', 'APPEARED', 'DISAPPEARED', 'STATUS_ONLY', name='change_type'), nullable=False),
    sa.Column('delta_qty', sa.Integer(), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_events_day', 'change_events', ['day'], unique=False)
    op.create_index('ix_change_events_product_day', 'change_events', ['product_id', 'day'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', 'ON_ORDER', 'MANY', 'UNKNOWN', name='stock_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'day', name='uq_snapshot_offer_day')
    )
    op.create_index('ix_snapshots_competitor_day', 'snapshots', ['competitor_id', 'day'], unique=False)
    op.create_index('ix_snapshots_product_day', 'snapshots', ['product_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_product_day', table_name='snapshots')
    op.drop_index('ix_snapshots_competitor_day', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('ix_change_events_product_day', table_name='change_events')
    op.drop_index('ix_change_events_day', table_name='change_events')
    op.drop_table('change_events')
    op.drop_table('product_metrics')
    op.drop_table('parse_runs')
    op.drop_index('ix_offers_product_competitor', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_products_oem', table_name='products')
    op.drop_index('ix_products_brand', table_name='products')
    op.drop_index('ix_products_article', table_name='products')
    op.drop_table('products')
    op.drop_table('competitors')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
